# See LICENSE file for full copyright and licensing details.
{
    'name': 'Do An Tot Nghiep',
    'version': "12.0.1.0.0",
    'author': "Nguyen Quang Duy",
    'category': 'Quản lý thư viện',
    'license': "AGPL-3",
    'summary': 'Ứng dụng quản lý thư viện cho trường học',
    'complexity': 'easy',
    'depends': ['base', 'mail', 'muk_web_searchpanel', 'web_notify', 'board', 'web_timeline', 'report_xlsx'],
    'data': [
        'security/library_security.xml',
        'data/data.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/mail_template.xml',
        'views/department.xml',
        'views/library_menu.xml',
        'views/library_duration.xml',
        'views/author.xml',
        'views/publisher.xml',
        'views/category.xml',
        'views/member.xml',
        'wizards/extend_library_card.xml',
        'views/card.xml',
        'data/library_card_schedular.xml',
        'wizards/create_meta_book.xml',
        'views/book.xml',
        'wizards/create_meta_project.xml',
        'views/project.xml',
        'views/magazine_newspaper.xml',
        'wizards/modify_descrip.xml',
        'wizards/send_by_email.xml',
        'views/checkout_at_lib.xml',
        'views/checkout_back_home.xml',
        'views/statistics.xml',
        'reports/library_card_report.xml',
        'reports/library_checkout_report.xml',
        'reports/penalty_checkout.xml',
    ],
    # 'demo': ['demo/data.xml'],
    # 'image': ['static/description/SchoolLibrary.png'],
    'installable': True,
    'application': True
}
